# -*- coding: utf-8 -*-
"""HW3_VAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HzUImM0S91JlX8SYAOrrq5QlCy80ntPe
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def VaR(r, confidence, principal = 1):
    # This function returns the left tail value and displays a histogram
    # r = a vector of stock returns
    # principal = investment initial value
  var_percentile=np.percentile(r,(1-confidence)*100)
  out=principal*abs(var_percentile)
  plt.hist(r, bins=50, alpha=0.75)
  plt.show()
    # out = principal * positively stated value of r at the 1-alpha percentile
  return out

r = np.random.normal(0.05, 0.03, 1000000)
probability2SD = norm.cdf(2)

my_confidence = probability2SD
my_percent_var = VaR(r, my_confidence)
print(np.round(my_percent_var, 2) == 0.01)

returns = np.random.normal(0, 1, 10000)
print(np.percentile(returns, 97.72))

