# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OFvFYVT0E-WUmCPDb6cIbSkQOfDpf5sa
"""

#whoami
def WhoAmI():
  return('yl5768')