# -*- coding: utf-8 -*-
"""HW3_getreturns.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sx2xcDW-8B7t9kcplWEznJYxlgWNzdeE
"""

import yfinance as yf
import pandas as pd
import numpy as np

def get_stock_data(symbol):
    
    if isinstance(symbol, str):
        data = yf.download(symbol)
        data.columns = data.columns.get_level_values(0)
        prices = data['Close']
    elif isinstance(symbol, pd.DataFrame):
        prices = symbol['Adj Close']

    return prices

def YahooData2returns(YahooData):
  adj_close=get_stock_data(YahooData)
  adj_close_values=adj_close.values
  n=len(adj_close_values)
  ratiovec=(adj_close_values[1:n]/adj_close_values[:n-1])
  returns=ratiovec-1
  return returns

YahooData2returns('GS')

